#!/bin/bash

# From Emil Thorenfeldt
# https://github.com/wonderfulspam/dotfiles/blob/master/git/prepare-commit-msg

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Only add custom message when there is no commit source
# Otherwise, keep the default message proposed by Git.
if [[ -z "$COMMIT_SOURCE" ]]; then
  # Get the branch name
  ref=$(git rev-parse --abbrev-ref HEAD)
  # Look for five consecutive digits in branch name
  if [[ $ref =~ ([0-9]{5}) ]]; then
    # Store original commit help text in temp string
    orig_msg=$(<"$COMMIT_MSG_FILE")
    # Extract ticket no. from regex match and wrap in [#]
    ticket="[#${BASH_REMATCH[1]}]"
    # Bring it all together
    echo "$ticket " > "$COMMIT_MSG_FILE"
    echo "$orig_msg" >> "$COMMIT_MSG_FILE"
  fi
fi
